apiVersion: batch/v1
kind: Job
metadata:
  name: bee-pretrain-test
spec:
  template:
    spec:
      containers:
      - name: animal2vec
        image: ccu-k8s.inf.uni-konstanz.de:32250/mattia.montanari/animal2vec:v2
        command: ["/bin/bash", "-c"]
        args:
          - |
            export HYDRA_FULL_ERROR=1
            export HF_HOME=/abyss/home/mattia-montanari/.cache/huggingface
            export TORCH_HOME=/abyss/home/mattia-montanari/.cache/torch
            export TMPDIR=/abyss/home/mattia-montanari/tmp
            mkdir -p $TMPDIR
            mkdir -p /abyss/home/checkpoints/bee-pretrain-test
            mkdir -p /abyss/home/tb_logs/bee-pretrain-test
            pip uninstall apex -y || true
            python /abyss/home/Sound-of-Bees/detection_through_deep_learning/animal2vec/animal2vec_train.py \
              --config-dir=/abyss/home/Sound-of-Bees/detection_through_deep_learning/animal2vec/configs/bees \
              --config-name=test_pretrain
        resources:
          requests:
            nvidia.com/gpu: 1
            cpu: "4"
            memory: "32Gi"
          limits:
            nvidia.com/gpu: 1
            cpu: "4"
            memory: "32Gi"
        volumeMounts:
          - mountPath: /abyss/home
            name: cephfs-home
            readOnly: false
          - mountPath: /abyss/shared
            name: cephfs-shared
            readOnly: false
          - mountPath: /abyss/datasets
            name: cephfs-datasets
            readOnly: true
      imagePullSecrets:
      - name: registry-ro-login
      restartPolicy: OnFailure
      volumes:
        - name: cephfs-home
          hostPath:
            path: "/cephfs/abyss/home/mattia-montanari"
            type: Directory
        - name: cephfs-shared
          hostPath:
            path: "/cephfs/abyss/shared"
            type: Directory
        - name: cephfs-datasets
          hostPath:
            path: "/cephfs/abyss/datasets"
            type: Directory

