apiVersion: v1
kind: Secret
metadata:
  name: cifs-secret
  namespace: user-mattia-montanari
type: fstab/cifs
data:
  username: 'MDAwOS0wMDA0LTQwMzUtNDQ3Ng=='
  password: 'UmVidWlsdC1SZW1lbWJlcjQtWW8teW8='
  domain: 'Q0FTQ0I='
