apiVersion: v1
kind: Pod                         #DSC change here for jobs
metadata:
  namespace: user-daniel-calovi   #DSC change here namespace
  name: ccu-deepseek-hpc  #DSC change here pod name
spec:
  nodeName: tiamat
  tolerations:
    - key: "gpumem"
      operator: "Equal"
      value: "40"
      effect: "NoSchedule"
  containers:
  - name: daniel-calovi-deepseek3-1     ##DSC change here
    image: git.cascb.uni-konstanz.de/0000-0002-2452-9801/ubuntu22_cuda12.2
    command: ["/bin/bash","-c"]
    args:
    - |
      /usr/sbin/sshd
      while true; do sleep 3600; done; # Keeps container running
    #args: ["while true; do sleep 30; done;"] # Keeps the container running
    resources:
      requests:
        cpu: 20
        nvidia.com/gpu: 1
        memory: 250Gi
      limits:
        cpu: 20
        nvidia.com/gpu: 1
        memory: 250Gi
    volumeMounts:
      - mountPath: /abyss/home
        name: cephfs-home
        readOnly: false
      - mountPath: /abyss/shared
        name: cephfs-shared
        readOnly: false
      - mountPath: /abyss/datasets
        name: cephfs-datasets
        readOnly: true
      - mountPath: "/abyss/home/pumbaa"
        name: samba-share
        readOnly: false
  imagePullSecrets:
  - name: regcredjson      			    #DSC change here for pull secrets
  volumes:
    - name: cephfs-home
      hostPath:
        path: "/cephfs/abyss/home/daniel-calovi"    #DSC change here your home
        type: Directory
    - name: cephfs-shared
      hostPath:
        path: "/cephfs/abyss/shared"
        type: Directory
    - name: cephfs-datasets
      hostPath:
        path: "/cephfs/abyss/datasets"
        type: Directory
    - name: samba-share			
      flexVolume:
        driver: "fstab/cifs"
        fsType: "cifs"
        secretRef:
          name: "cifs-secret"
        options:
          networkPath: "//Timon.cascb.uni-konstanz.de/SSD_WIP"
          mountOptions: "vers=3.0,dir_mode=0755,file_mode=0644,noperm,domain=CASCB"
