apiVersion: v1
kind: Pod
metadata:
  name: name-for-my-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: asmodeus
  tolerations:
  - key: "gpumem"
    operator: "Equal"
    value: "80"
    effect: "NoSchedule"
  containers:
  - name: name-for-my-container-on-my-pod
    image: nvcr.io/nvidia/pytorch:22.11-py3  # This has PyTorch 1.13 running
    command: ["/bin/sh"]
    args: ["-c", "/path/to/example_launch_script.sh"]
    resources:
      requests:
        cpu: 50
        nvidia.com/gpu: 4
        memory: 1024Gi
      limits:
        cpu: 50
        nvidia.com/gpu: 4
        memory: 1024Gi
    volumeMounts:
      - mountPath: /abyss/home
        name: cephfs-home
        readOnly: false
      - mountPath: /abyss/shared
        name: cephfs-shared
        readOnly: false
      - mountPath: /abyss/datasets
        name: cephfs-datasets
        readOnly: true
      - mountPath: /local
        name: local-storage
        readOnly: false
      - mountPath: /dev/shm
        name: dshm
    ports:
      - containerPort: 8080
  restartPolicy: Never
  volumes:
    - name: cephfs-home
      hostPath:
        path: "/cephfs/abyss/home/YOUR-USERNAME"
        type: Directory
    - name: cephfs-shared
      hostPath:
        path: "/cephfs/abyss/shared"
        type: Directory
    - name: cephfs-datasets
      hostPath:
        path: "/cephfs/abyss/datasets"
        type: Directory
    - name: local-storage
      hostPath:
        path: "/raid/local-data/YOUR-USERNAME"
        type: DirectoryOrCreate
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 64Gi