apiVersion: v1
kind: Pod
metadata:
  name: busybox-test-pod
spec:
  containers:
  - name: busybox
    image: ccu-k8s.inf.uni-konstanz.de:32250/mattia.montanari/my_busybox  #change busybox to whatever the name of your custom container is
    command: ["sleep", "1d"]
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1
        memory: 1Gi
    volumeMounts:
      - mountPath: /abyss/home
        name: cephfs-home
        readOnly: false
      - mountPath: /abyss/shared
        name: cephfs-shared
        readOnly: false
      - mountPath: /abyss/datasets
        name: cephfs-datasets
        readOnly: true
  imagePullSecrets:                     #Secret to your repository here
  - name: "registry-ro-login"      #Name you have chosen for your secret
  volumes:
    - name: cephfs-home
      hostPath:
        path: "/cephfs/abyss/home/mattia-montanari"
        type: Directory
    - name: cephfs-shared
      hostPath:
        path: "/cephfs/abyss/shared"
        type: Directory
    - name: cephfs-datasets
      hostPath:
        path: "/cephfs/abyss/datasets"
        type: Directory
