apiVersion: v1
kind: Pod
metadata:
  name: animal2vec-interactive
spec:
  containers:
  - name: animal2vec
    image: ccu-k8s.inf.uni-konstanz.de:32250/mattia.montanari/animal2vec:v3
    command: ["sleep", "7d"]
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 4
        memory: 16Gi
    volumeMounts:
      - mountPath: /abyss/home
        name: cephfs-home
        readOnly: false
      - mountPath: /abyss/shared
        name: cephfs-shared
        readOnly: false
      - mountPath: /abyss/datasets
        name: cephfs-datasets
        readOnly: true
  imagePullSecrets:
  - name: registry-ro-login
  volumes:
    - name: cephfs-home
      hostPath:
        path: "/cephfs/abyss/home/mattia-montanari"
        type: Directory
    - name: cephfs-shared
      hostPath:
        path: "/cephfs/abyss/shared"
        type: Directory
    - name: cephfs-datasets
      hostPath:
        path: "/cephfs/abyss/datasets"
        type: Directory

