apiVersion: v1
kind: Pod
metadata:
  namespace: user-mattia-montanari
  name: vecna-local-storage-interaction
spec:
  nodeName: vecna                         # ← forza il pod su vecna
  tolerations:
    - key: "gpumem"                        # ← serve per passare il taint di tiamat
      operator: "Equal"
      value: "40"
      effect: "NoSchedule"
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    command: ["sleep", "7d"]               # pod vivo per 7 giorni
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 4Gi
    volumeMounts:
      - mountPath: /abyss/home
        name: cephfs-home
        readOnly: false
      - mountPath: /abyss/shared
        name: cephfs-shared
        readOnly: false
      - mountPath: /abyss/datasets
        name: cephfs-datasets
        readOnly: true
      - mountPath: /local                  # ← qui vedi il fast storage di tiamat
        name: local-storage
        readOnly: false
  volumes:
    - name: cephfs-home
      hostPath:
        path: "/cephfs/abyss/home/mattia-montanari"
        type: Directory
    - name: cephfs-shared
      hostPath:
        path: "/cephfs/abyss/shared"
        type: Directory
    - name: cephfs-datasets
      hostPath:
        path: "/cephfs/abyss/datasets"
        type: Directory
    - name: local-storage
      hostPath:
        path: "/raid/local-data/mattia-montanari"   # fast storage locale su tiamat
        type: DirectoryOrCreate

